version: "3.8"
services:
  # Postgres SQL Database
  db:
    image: postgres:15-alpine
    container_name: exam_engine_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exam_engine_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
